In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict([[5000]])

array([859554.79452055])

In [7]:
#Save Model To a File Using Python Pickle
import pickle

In [8]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [9]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [10]:
mp.coef_

array([135.78767123])

In [11]:
mp.intercept_

180616.43835616432

In [12]:
mp.predict([[5000]])

array([859554.79452055])

In [13]:
#Save Trained Model Using joblib
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\Upama\Anaconda3\lib\site-packages\sklearn\externals\__init__.py)